#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.

#Your script should only display:

#username
#user id
#Home directory path for the user
#Requirements:

#You must use the while loop (for and until are forbidden)
i=1;
while ((i ==1)); do
    cat /etc/passwd | cut -d : -f 1,3,6
    i=0;
done
