#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd,# using the while loop + IFS.

#Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_D#IRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the p#asscode PASSWORD, more info about the user here: USER ID INFO

#Requirements:

#You must use the while loop (for and until are forbidden)


IFS=":"
while read -r username password user_id group_id user_id_info home_directory commandshell; do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $commandshell. $user_id's place is protected by the passcode $password, more info about the user here: $user_id_info"

done < /etc/passwd
