#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes using while loop and :

# display hours from 0 to 12
# display minutes from 1 to 59

h=0
while ((h <= 12));do
    echo "Hour: $h"
    m=1
    while ((m <= 59));do
	echo $m
	m=$((m+1))
    done
    h=$((h+1))
done

    
