#!/usr/bin/env bash
#script that displays The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
# Using for loop

for i in $(ls); do
    echo $i | cut -d "-" -f 2-
done
