#!/usr/bin/env bash
#Bash (init) script 11-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

#Requirements:

#When passing the argument start:
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process started
#When passing the argument stop:
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Displays manage_my_process stopped
#When passing the argument restart
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process restarted
#Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

start () {
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop () {
    pkill -f ./manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restart () {
    pkill -f ./manage_my_process    
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! >> /var/run/my_process.pid
    echo "manage_my_process restarted"
}

case "$1" in
   start) start ;;
   stop)  stop;;
   restart) restart;;
   *) echo "Usage: manage_my_process {start|stop|restart}"
      exit 1
      ;;
esac
