#!/usr/bin/env bash

start () {
    ./manage_my_process &
    echo $$ >> /var/run/my_process.pid
    echo "manage_my_process started"
}

stop () {
    pkill -f ./manage_my_process
    sudo rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restart () {
    pkill -f ./manage_my_process    
    rm /var/run/my_process.pid
    ./manage_my_process &
  sudo echo $$ >> /var/run/my_process.pid
    echo "manage_my_process restarted"
}

case "$1" in
   start) start ;;
   stop)  stop;;
   restart) restart;;
   *) echo "Usage $0 (start|stop|restart)"
      exit 1
      ;;
esac
