#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process, with kill
# shellcheck disable=SC2009
# shellcheck disable=SC2046
# To get the specific name of the wcript i used ps aux to display all processes witrh their information, grep to look for the name of the script and print it, and awk to print the positionnal parameter $2 which is the PID.
# I use then kill on the result of this set of commands with kill $(cmd)
kill $(ps aux | grep '[b]ash ./4*' | awk '{print $2}')

#BETTER WAY AND EASIER : kill $(pgrep -f ./4) ==> pgrep -f look for ./4 in all full command lines .
