#!/usr/bin/env bash

start () {
    ./script &
    echo $$ >> my_process
    echo "$(pgrep -f $$ | awk '{print $2}') started"
}

stop () {
    kill $!
    rm my_process
    echo "$! stopped"
}

restart () {
    kill $!
    rm my_process
    ./script &
    echo $$ >> my_process
    echo "$! started"
}

case "$1" in
   start) start ;;
   stop)  stop;;
   restart) restart;;
   *) echo "Usage $0 (start|stop|restart)"
      exit 1
      ;;
esac
