#!/usr/bin/env bash

start () {
    ./test &
    echo $$ >> my_process
    echo "test started"
}

stop () {
    pkill -f ./test
    rm my_process
    echo "test stopped"
}

restart () {
    pkill -f ./test
    rm my_process
    ./test &
    echo $$ >> my_process
    echo "test restarted"
}

case "$1" in
   start) start ;;
   stop)  stop;;
   restart) restart;;
   *) echo "Usage $0 (start|stop|restart)"
      exit 1
      ;;
esac
